package com.nrabello.ecommerceLivraria.model;

public enum EOrderStatus {
    EM_PROCESSAMENTO,
    APROVADA,
    REPROVADA,
    EM_TRANSITO,
    ENTREGUE,
    EM_TROCA,
    EM_DEVOLUCAO,
    TROCA_AUTORIZADA,
    TROCA_NEGADA,
    DEVOLUCAO_AUTORIZADA,
    DEVOLUCAO_NEGADA,
    PRODUTOS_RECEBIDOS,
    EM_TRANSPORTE,
    TROCADO,
    CANCELADO,
    DEVOLVIDO,
    ITENS_ENVIADOS_TROCA,
    ITENS_RECEBIDOS_TROCA,
    ITENS_ENVIADOS_DEVOLUCAO,
    ITENS_RECEBIDOS_DEVOLUCAO
}
